name: crazyswarm
channels:
  - conda-forge
dependencies:
  - python=2.7
  - numpy
  - scipy
  - matplotlib=2.1  # VisPy not compatible with newer versions
  - vispy
  - pyyaml
  - swig
  - sphinx
  - sphinx_rtd_theme
  - pyqt
  - sphinx-argparse
  - pytest
