name: crazyswarm
dependencies:
  - numpy
  - matplotlib
  - vispy
  - pyyaml
  - swig
  - sphinx
  - sphinx_rtd_theme
  - pyqt
  - conda-forge::sphinx-argparse
  - pytest
  - snakeviz
  - scipy
  - cvxopt
  - mosek::mosek
  - networkx
  - picos::picos
  - pip
  - pip:
    - quadpy==0.12
